### ISSUE TITLE
Bot is down

### ISSUE THREAD

**Issue by KnorpelSenf** [garboh/pwned_robot#3]
Are you already aware of it? Are you working on it? Is there anything we can do to help?

**Comment by KnorpelSenf** [comment]
Expected to be back up on Sunday.

**Comment by garboh** [comment]
I have restored the main functions of the bot.
They are now accessible via these commands:

/email [_your_email_here_] - check your email in a data breach
/password [_your_password_] - check your password in a data breach
/phone [_your_phone_numer_] - check your phone number in a data breach (phone number must be in **international format**)

I remember it's a temporary release as I'm rewriting the whole code to be in line with python-telegram-bot v 20.1
